{ SOUTH CAROLINA: 
   [ 'TOBACCO',
     'COTTON',
     'WHEAT',
     'PEANUTS',
     'SOYBEANS',
     'OATS',
     'HAY',
     'CORN',
     'SORGHUM',
     'HAY & HAYLAGE',
     'FIELD CROP TOTALS' ],
  INDIANA: 
   [ 'HAY',
     'SOYBEANS',
     'CORN',
     'WHEAT',
     'OATS',
     'TOBACCO',
     'MINT',
     'FIELD CROP TOTALS',
     'HAY & HAYLAGE' ],
  OKLAHOMA: 
   [ 'HAY',
     'WHEAT',
     'HAY & HAYLAGE',
     'CORN',
     'SOYBEANS',
     'FIELD CROP TOTALS',
     'OATS',
     'SORGHUM',
     'PEANUTS',
     'SUNFLOWER',
     'COTTON',
     'RYE',
     'CANOLA',
     'BARLEY' ],
  KENTUCKY: 
   [ 'WHEAT',
     'HAY',
     'TOBACCO',
     'BARLEY',
     'SOYBEANS',
     'SORGHUM',
     'CORN',
     'HAY & HAYLAGE',
     'FIELD CROP TOTALS' ],
  MISSOURI: 
   [ 'COTTON',
     'HAY',
     'RICE',
     'TOBACCO',
     'CORN',
     'WHEAT',
     'FIELD CROP TOTALS',
     'SORGHUM',
     'OATS',
     'SOYBEANS',
     'HAYLAGE',
     'HAY & HAYLAGE' ],
  ARKANSAS: 
   [ 'RICE',
     'COTTON',
     'CORN',
     'OATS',
     'SOYBEANS',
     'WHEAT',
     'HAY',
     'SORGHUM',
     'FIELD CROP TOTALS',
     'HAY & HAYLAGE' ],
  DELAWARE: 
   [ 'WHEAT',
     'CORN',
     'FIELD CROP TOTALS',
     'SOYBEANS',
     'HAY',
     'BARLEY',
     'SORGHUM',
     'HAY & HAYLAGE' ],
  OTHER STATES: 
   [ 'SUNFLOWER',
     'SAFFLOWER',
     'SORGHUM',
     'RYE',
     'CANOLA',
     'HAY',
     'WHEAT',
     'BEANS',
     'CORN',
     'OATS',
     'TOBACCO',
     'BARLEY',
     'SOYBEANS',
     'MINT',
     'COTTON',
     'PEANUTS',
     'RICE',
     'PEAS' ],
  NORTH DAKOTA: 
   [ 'BEANS',
     'SOYBEANS',
     'LENTILS',
     'CORN',
     'HAY',
     'PEAS',
     'OATS',
     'BARLEY',
     'WHEAT',
     'SUNFLOWER',
     'SUGARBEETS',
     'RYE',
     'CANOLA',
     'FLAXSEED',
     'SAFFLOWER',
     'HAY & HAYLAGE',
     'FIELD CROP TOTALS' ],
  FLORIDA: 
   [ 'WHEAT',
     'TOBACCO',
     'SUGARCANE',
     'FIELD CROP TOTALS',
     'COTTON',
     'SOYBEANS',
     'PEANUTS',
     'CORN',
     'HAY',
     'HAY & HAYLAGE' ],
  SOUTH DAKOTA: 
   [ 'BEANS',
     'HAYLAGE',
     'CORN',
     'SORGHUM',
     'FIELD CROP TOTALS',
     'SOYBEANS',
     'WHEAT',
     'HAY & HAYLAGE',
     'OATS',
     'SUNFLOWER',
     'MILLET',
     'HAY',
     'FLAXSEED',
     'BARLEY',
     'RYE' ],
  IDAHO: 
   [ 'LENTILS',
     'BEANS',
     'WHEAT',
     'SUGARBEETS',
     'PEAS',
     'HOPS',
     'HAY',
     'BARLEY',
     'OATS',
     'MINT',
     'CORN',
     'CANOLA',
     'HAYLAGE',
     'HAY & HAYLAGE',
     'FIELD CROP TOTALS' ],
  WASHINGTON: 
   [ 'LENTILS',
     'FIELD CROP TOTALS',
     'BEANS',
     'CORN',
     'WHEAT',
     'HAY',
     'MINT',
     'HAY & HAYLAGE',
     'HOPS',
     'SUGARBEETS',
     'PEAS',
     'HAYLAGE',
     'BARLEY',
     'OATS',
     'CANOLA' ],
  MONTANA: 
   [ 'LENTILS',
     'SUGARBEETS',
     'BEANS',
     'WHEAT',
     'PEAS',
     'FIELD CROP TOTALS',
     'HAY',
     'FLAXSEED',
     'CANOLA',
     'HAY & HAYLAGE',
     'OATS',
     'CORN',
     'SAFFLOWER',
     'BARLEY',
     'MUSTARD',
     'SUNFLOWER' ],
  KANSAS: 
   [ 'HAY',
     'SOYBEANS',
     'SUNFLOWER',
     'BEANS',
     'SORGHUM',
     'CORN',
     'BARLEY',
     'OATS',
     'WHEAT',
     'COTTON',
     'HAY & HAYLAGE',
     'HAYLAGE',
     'FIELD CROP TOTALS' ],
  MISSISSIPPI: 
   [ 'RICE',
     'COTTON',
     'WHEAT',
     'HAY',
     'PEANUTS',
     'SORGHUM',
     'SOYBEANS',
     'CORN',
     'FIELD CROP TOTALS',
     'HAY & HAYLAGE' ],
  CALIFORNIA: 
   [ 'RICE',
     'SORGHUM',
     'SUNFLOWER',
     'COTTON',
     'BEANS',
     'HAY',
     'CORN',
     'HAYLAGE',
     'WHEAT',
     'OATS',
     'BARLEY',
     'SUGARBEETS',
     'SAFFLOWER',
     'HAY & HAYLAGE',
     'FIELD CROP TOTALS',
     'MINT' ],
  TEXAS: 
   [ 'HAY',
     'BEANS',
     'COTTON',
     'CORN',
     'OATS',
     'RICE',
     'SUNFLOWER',
     'SORGHUM',
     'FIELD CROP TOTALS',
     'WHEAT',
     'SOYBEANS',
     'PEANUTS',
     'SUGARCANE',
     'HAYLAGE',
     'HAY & HAYLAGE' ],
  ILLINOIS: 
   [ 'HAYLAGE',
     'HAY & HAYLAGE',
     'CORN',
     'WHEAT',
     'SORGHUM',
     'OATS',
     'HAY',
     'SOYBEANS',
     'FIELD CROP TOTALS' ],
  NEW MEXICO: 
   [ 'BEANS',
     'HAY',
     'COTTON',
     'CORN',
     'WHEAT',
     'PEANUTS',
     'SORGHUM',
     'FIELD CROP TOTALS',
     'HAYLAGE',
     'HAY & HAYLAGE' ],
  CONNECTICUT: 
   [ 'HAY',
     'TOBACCO',
     'FIELD CROP TOTALS',
     'MAPLE SYRUP',
     'CORN',
     'HAY & HAYLAGE' ],
  NEVADA: 
   [ 'HAY',
     'CORN',
     'BARLEY',
     'WHEAT',
     'FIELD CROP TOTALS',
     'HAY & HAYLAGE' ],
  UTAH: 
   [ 'BARLEY',
     'FIELD CROP TOTALS',
     'HAY',
     'CORN',
     'SAFFLOWER',
     'WHEAT',
     'BEANS',
     'OATS',
     'HAY & HAYLAGE' ],
  OREGON: 
   [ 'BEANS',
     'PEAS',
     'HOPS',
     'MINT',
     'SUGARBEETS',
     'OATS',
     'BARLEY',
     'CORN',
     'HAY',
     'WHEAT',
     'CANOLA',
     'FIELD CROP TOTALS',
     'HAY & HAYLAGE' ],
  MASSACHUSETTS: 
   [ 'HAY',
     'MAPLE SYRUP',
     'TOBACCO',
     'HAY & HAYLAGE',
     'FIELD CROP TOTALS',
     'CORN' ],
  MICHIGAN: 
   [ 'HAY',
     'BEANS',
     'SOYBEANS',
     'MINT',
     'HAY & HAYLAGE',
     'WHEAT',
     'OATS',
     'MAPLE SYRUP',
     'BARLEY',
     'CORN',
     'SUGARBEETS',
     'FIELD CROP TOTALS',
     'HAYLAGE' ],
  NEW JERSEY: 
   [ 'CORN',
     'FIELD CROP TOTALS',
     'SOYBEANS',
     'HAY',
     'BARLEY',
     'WHEAT',
     'HAY & HAYLAGE' ],
  VIRGINIA: 
   [ 'TOBACCO',
     'COTTON',
     'HAY',
     'WHEAT',
     'SORGHUM',
     'OATS',
     'PEANUTS',
     'SOYBEANS',
     'CORN',
     'BARLEY',
     'HAY & HAYLAGE',
     'FIELD CROP TOTALS' ],
  NORTH CAROLINA: 
   [ 'PEANUTS',
     'COTTON',
     'TOBACCO',
     'HAY & HAYLAGE',
     'HAY',
     'CORN',
     'WHEAT',
     'BARLEY',
     'OATS',
     'SORGHUM',
     'SOYBEANS',
     'FIELD CROP TOTALS' ],
  IOWA: 
   [ 'SOYBEANS',
     'HAY',
     'CORN',
     'OATS',
     'WHEAT',
     'HAY & HAYLAGE',
     'HAYLAGE',
     'FIELD CROP TOTALS' ],
  WISCONSIN: 
   [ 'TOBACCO',
     'SOYBEANS',
     'BEANS',
     'WHEAT',
     'BARLEY',
     'HAY',
     'MAPLE SYRUP',
     'HAY & HAYLAGE',
     'CORN',
     'OATS',
     'MINT',
     'FIELD CROP TOTALS',
     'HAYLAGE' ],
  MARYLAND: 
   [ 'CORN',
     'BARLEY',
     'FIELD CROP TOTALS',
     'WHEAT',
     'HAY',
     'SOYBEANS',
     'TOBACCO',
     'SORGHUM',
     'HAY & HAYLAGE' ],
  GEORGIA: 
   [ 'PEANUTS',
     'TOBACCO',
     'COTTON',
     'SOYBEANS',
     'HAY',
     'WHEAT',
     'CORN',
     'RYE',
     'SORGHUM',
     'OATS',
     'FIELD CROP TOTALS',
     'HAY & HAYLAGE' ],
  MINNESOTA: 
   [ 'HAY',
     'BEANS',
     'WHEAT',
     'BARLEY',
     'SUNFLOWER',
     'HAY & HAYLAGE',
     'SUGARBEETS',
     'CANOLA',
     'SOYBEANS',
     'CORN',
     'OATS',
     'FLAXSEED',
     'HAYLAGE',
     'FIELD CROP TOTALS' ],
  WEST VIRGINIA: 
   [ 'TOBACCO',
     'WHEAT',
     'HAY',
     'SOYBEANS',
     'CORN',
     'HAY & HAYLAGE',
     'FIELD CROP TOTALS',
     'HAYLAGE' ],
  OHIO: 
   [ 'TOBACCO',
     'WHEAT',
     'FIELD CROP TOTALS',
     'MAPLE SYRUP',
     'CORN',
     'HAY',
     'OATS',
     'SOYBEANS',
     'SUGARBEETS',
     'BARLEY',
     'HAYLAGE',
     'HAY & HAYLAGE' ],
  TENNESSEE: 
   [ 'COTTON',
     'HAY',
     'TOBACCO',
     'WHEAT',
     'SORGHUM',
     'CORN',
     'SOYBEANS',
     'FIELD CROP TOTALS',
     'HAY & HAYLAGE' ],
  NEBRASKA: 
   [ 'BEANS',
     'CORN',
     'WHEAT',
     'SORGHUM',
     'SOYBEANS',
     'SUNFLOWER',
     'HAY',
     'SUGARBEETS',
     'OATS',
     'HAY & HAYLAGE',
     'BARLEY',
     'MILLET',
     'HAYLAGE',
     'FIELD CROP TOTALS' ],
  WYOMING: 
   [ 'BEANS',
     'SUGARBEETS',
     'WHEAT',
     'HAY',
     'CORN',
     'BARLEY',
     'OATS',
     'FIELD CROP TOTALS',
     'HAY & HAYLAGE' ],
  COLORADO: 
   [ 'BEANS',
     'WHEAT',
     'HAY',
     'SUNFLOWER',
     'OATS',
     'CORN',
     'SUGARBEETS',
     'SORGHUM',
     'BARLEY',
     'MILLET',
     'FIELD CROP TOTALS',
     'HAY & HAYLAGE' ],
  ARIZONA: 
   [ 'HAY',
     'WHEAT',
     'COTTON',
     'CORN',
     'SORGHUM',
     'BARLEY',
     'BEANS',
     'HAY & HAYLAGE',
     'FIELD CROP TOTALS' ],
  VERMONT: 
   [ 'MAPLE SYRUP',
     'HAY',
     'CORN',
     'HAYLAGE',
     'FIELD CROP TOTALS',
     'HAY & HAYLAGE' ],
  LOUISIANA: 
   [ 'CORN',
     'COTTON',
     'RICE',
     'HAY',
     'SUGARCANE',
     'SORGHUM',
     'WHEAT',
     'SOYBEANS',
     'FIELD CROP TOTALS',
     'HAY & HAYLAGE' ],
  RHODE ISLAND: [ 'HAY', 'CORN', 'FIELD CROP TOTALS', 'HAY & HAYLAGE' ],
  NEW YORK: 
   [ 'CORN',
     'OATS',
     'FIELD CROP TOTALS',
     'HAY',
     'BEANS',
     'MAPLE SYRUP',
     'WHEAT',
     'BARLEY',
     'SOYBEANS',
     'HAY & HAYLAGE',
     'HAYLAGE' ],
  ALABAMA: 
   [ 'OATS',
     'PEANUTS',
     'COTTON',
     'SORGHUM',
     'SOYBEANS',
     'HAY',
     'FIELD CROP TOTALS',
     'CORN',
     'WHEAT',
     'HAY & HAYLAGE' ],
  HAWAII: [ 'SUGARCANE', 'TARO', 'FIELD CROP TOTALS' ],
  PENNSYLVANIA: 
   [ 'HAY & HAYLAGE',
     'OATS',
     'WHEAT',
     'HAYLAGE',
     'SOYBEANS',
     'CORN',
     'HAY',
     'SORGHUM',
     'BARLEY',
     'TOBACCO',
     'MAPLE SYRUP',
     'FIELD CROP TOTALS' ],
  NEW HAMPSHIRE: 
   [ 'HAY',
     'HAY & HAYLAGE',
     'MAPLE SYRUP',
     'CORN',
     'FIELD CROP TOTALS' ],
  MAINE: 
   [ 'HAY',
     'OATS',
     'MAPLE SYRUP',
     'BARLEY',
     'HAY & HAYLAGE',
     'FIELD CROP TOTALS',
     'CORN' ],
  ALASKA: [ 'HAY', 'BARLEY', 'OATS' ] }