var selectionData = {'FRUIT%20%26%20TREE%20NUTS':[{ 'NORTH CAROLINA':  [ 'APPLES',
     'PEACHES',
     'STRAWBERRIES',
     'FRUIT & TREE NUT TOTALS',
     'PECANS',
     'GRAPES',
     'BLUEBERRIES',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  MASSACHUSETTS: 
   [ 'PEARS',
     'APPLES',
     'BLUEBERRIES',
     'PEACHES',
     'STRAWBERRIES',
     'CRANBERRIES',
     'FRUIT & TREE NUT TOTALS',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  MAINE: 
   [ 'BLUEBERRIES',
     'PEACHES',
     'STRAWBERRIES',
     'PEARS',
     'APPLES',
     'FRUIT & TREE NUT TOTALS',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  'NEW HAMPSHIRE': 
   [ 'PEACHES',
     'APPLES',
     'PEARS',
     'STRAWBERRIES',
     'BLUEBERRIES',
     'FRUIT & TREE NUT TOTALS',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  'NEW YORK': 
   [ 'PEARS',
     'APPLES',
     'GRAPES',
     'PEACHES',
     'CHERRIES',
     'STRAWBERRIES',
     'BLUEBERRIES',
     'FRUIT & TREE NUT TOTALS',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  VERMONT: 
   [ 'PEACHES',
     'PEARS',
     'STRAWBERRIES',
     'APPLES',
     'BLUEBERRIES',
     'FRUIT & TREE NUT TOTALS',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  GEORGIA: 
   [ 'PEACHES',
     'BLUEBERRIES',
     'PECANS',
     'GRAPES',
     'APPLES',
     'FRUIT & TREE NUT TOTALS',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  'NEW JERSEY': 
   [ 'APPLES',
     'PEACHES',
     'FRUIT & TREE NUT TOTALS',
     'STRAWBERRIES',
     'CRANBERRIES',
     'BLUEBERRIES',
     'GRAPES',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  'WEST VIRGINIA': 
   [ 'PEACHES',
     'APPLES',
     'FRUIT & TREE NUT TOTALS',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  MARYLAND: 
   [ 'PEACHES',
     'APPLES',
     'STRAWBERRIES',
     'FRUIT & TREE NUT TOTALS',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  'RHODE ISLAND': 
   [ 'APPLES',
     'PEACHES',
     'STRAWBERRIES',
     'PEARS',
     'BLUEBERRIES',
     'FRUIT & TREE NUT TOTALS',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  LOUISIANA: 
   [ 'PEACHES',
     'PECANS',
     'STRAWBERRIES',
     'FRUIT & TREE NUT TOTALS',
     'ORANGES',
     'APPLES',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  'SOUTH CAROLINA': 
   [ 'PEACHES',
     'PECANS',
     'FRUIT & TREE NUT TOTALS',
     'APPLES',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  VIRGINIA: 
   [ 'APPLES',
     'GRAPES',
     'STRAWBERRIES',
     'PEACHES',
     'FRUIT & TREE NUT TOTALS',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  FLORIDA: 
   [ 'CITRUS TOTALS',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS',
     'ORANGES',
     'STRAWBERRIES',
     'PECANS',
     'AVOCADOS',
     'BLUEBERRIES',
     'GRAPEFRUIT',
     'TANGERINES',
     'TANGELOS',
     'FRUIT & TREE NUT TOTALS',
     'K-EARLY CITRUS',
     'TEMPLES',
     'LIMES' ],
  CONNECTICUT: 
   [ 'PEARS',
     'APPLES',
     'STRAWBERRIES',
     'BLUEBERRIES',
     'PEACHES',
     'FRUIT & TREE NUT TOTALS',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  CALIFORNIA: 
   [ 'KIWIFRUIT',
     'ORANGES',
     'LEMONS',
     'STRAWBERRIES',
     'TANGERINES',
     'ALMONDS',
     'DATES',
     'PECANS',
     'WALNUTS',
     'PLUMS',
     'PRUNES',
     'GRAPES',
     'RASPBERRIES',
     'AVOCADOS',
     'FIGS',
     'OLIVES',
     'APPLES',
     'APRICOTS',
     'NECTARINES',
     'PEARS',
     'BLUEBERRIES',
     'GRAPEFRUIT',
     'PISTACHIOS',
     'PEACHES',
     'CHERRIES',
     'CITRUS TOTALS',
     'BOYSENBERRIES',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS',
     'FRUIT & TREE NUT TOTALS' ],
  HAWAII: 
   [ 'COFFEE',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS',
     'FRUIT & TREE NUT TOTALS',
     'MACADAMIAS',
     'PINEAPPLES',
     'PAPAYAS',
     'AVOCADOS',
     'BANANAS',
     'GUAVAS' ],
  PENNSYLVANIA: 
   [ 'PEACHES',
     'APPLES',
     'STRAWBERRIES',
     'GRAPES',
     'PEARS',
     'CHERRIES',
     'FRUIT & TREE NUT TOTALS',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  DELAWARE: [ 'APPLES', 'STRAWBERRIES', 'PEACHES', 'FRUIT & TREE NUT TOTALS' ],
  TEXAS: 
   [ 'PECANS',
     'GRAPES',
     'GRAPEFRUIT',
     'PEACHES',
     'ORANGES',
     'CITRUS TOTALS',
     'FRUIT & TREE NUT TOTALS',
     'APPLES',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  MISSISSIPPI: 
   [ 'NON-CITRUS FRUIT & TREE NUTS TOTALS',
     'BLUEBERRIES',
     'PECANS',
     'FRUIT & TREE NUT TOTALS',
     'APPLES',
     'ORANGES' ],
  UTAH: 
   [ 'APPLES',
     'CHERRIES',
     'APRICOTS',
     'PEACHES',
     'FRUIT & TREE NUT TOTALS',
     'PEARS',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  MICHIGAN: 
   [ 'NON-CITRUS FRUIT & TREE NUTS TOTALS',
     'STRAWBERRIES',
     'PLUMS & PRUNES',
     'GRAPES',
     'BLUEBERRIES',
     'PEACHES',
     'CHERRIES',
     'PEARS',
     'APPLES',
     'FRUIT & TREE NUT TOTALS' ],
  'NEW MEXICO': 
   [ 'PECANS',
     'FRUIT & TREE NUT TOTALS',
     'APPLES',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  OREGON: 
   [ 'STRAWBERRIES',
     'FRUIT & TREE NUT TOTALS',
     'RASPBERRIES',
     'CRANBERRIES',
     'HAZELNUTS',
     'BLUEBERRIES',
     'APPLES',
     'CHERRIES',
     'BOYSENBERRIES',
     'PEARS',
     'BLACKBERRIES',
     'GRAPES',
     'PLUMS & PRUNES',
     'PEACHES',
     'LOGANBERRIES',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  OKLAHOMA: 
   [ 'PECANS',
     'FRUIT & TREE NUT TOTALS',
     'PEACHES',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS',
     'APPLES' ],
  WASHINGTON: 
   [ 'STRAWBERRIES',
     'FRUIT & TREE NUT TOTALS',
     'PLUMS & PRUNES',
     'GRAPES',
     'CRANBERRIES',
     'RASPBERRIES',
     'APRICOTS',
     'NECTARINES',
     'PEARS',
     'BLUEBERRIES',
     'PEACHES',
     'CHERRIES',
     'APPLES',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS',
     'HAZELNUTS' ],
  OHIO: 
   [ 'STRAWBERRIES',
     'FRUIT & TREE NUT TOTALS',
     'GRAPES',
     'PEACHES',
     'APPLES',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS',
     'CHERRIES' ],
  WISCONSIN: 
   [ 'STRAWBERRIES',
     'CRANBERRIES',
     'CHERRIES',
     'APPLES',
     'FRUIT & TREE NUT TOTALS',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  ILLINOIS: 
   [ 'FRUIT & TREE NUT TOTALS',
     'APPLES',
     'PEACHES',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  'NORTH DAKOTA': [ 'FRUIT & TREE NUT TOTALS' ],
  MONTANA: 
   [ 'FRUIT & TREE NUT TOTALS',
     'CHERRIES',
     'APPLES',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  TENNESSEE: 
   [ 'FRUIT & TREE NUT TOTALS',
     'APPLES',
     'PEACHES',
     'STRAWBERRIES',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  IDAHO: 
   [ 'FRUIT & TREE NUT TOTALS',
     'PLUMS & PRUNES',
     'PEACHES',
     'CHERRIES',
     'APPLES',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  MISSOURI: 
   [ 'FRUIT & TREE NUT TOTALS',
     'PECANS',
     'GRAPES',
     'PEACHES',
     'APPLES',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  ARKANSAS: 
   [ 'PECANS',
     'STRAWBERRIES',
     'GRAPES',
     'BLUEBERRIES',
     'PEACHES',
     'FRUIT & TREE NUT TOTALS',
     'APPLES',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  IOWA: 
   [ 'APPLES',
     'FRUIT & TREE NUT TOTALS',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  MINNESOTA: 
   [ 'APPLES',
     'FRUIT & TREE NUT TOTALS',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  ALABAMA: 
   [ 'PECANS',
     'BLUEBERRIES',
     'PEACHES',
     'FRUIT & TREE NUT TOTALS',
     'APPLES',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS',
     'ORANGES' ],
  ARIZONA: 
   [ 'PECANS',
     'LEMONS',
     'APPLES',
     'TANGERINES',
     'ORANGES',
     'GRAPEFRUIT',
     'FRUIT & TREE NUT TOTALS',
     'CITRUS TOTALS',
     'GRAPES',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  INDIANA: 
   [ 'BLUEBERRIES',
     'APPLES',
     'FRUIT & TREE NUT TOTALS',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS',
     'PEACHES' ],
  KANSAS: 
   [ 'PECANS',
     'FRUIT & TREE NUT TOTALS',
     'APPLES',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  'OTHER STATES': 
   [ 'APPLES',
     'PEACHES',
     'GRAPES',
     'CHERRIES',
     'STRAWBERRIES',
     'BLUEBERRIES',
     'PECANS' ],
  COLORADO: 
   [ 'PEACHES',
     'APPLES',
     'FRUIT & TREE NUT TOTALS',
     'PEARS',
     'CHERRIES',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  KENTUCKY: 
   [ 'FRUIT & TREE NUT TOTALS',
     'PEACHES',
     'APPLES',
     'STRAWBERRIES',
     'NON-CITRUS FRUIT & TREE NUTS TOTALS' ],
  WYOMING: [ 'FRUIT & TREE NUT TOTALS', 'APPLES' ],
  NEBRASKA: [ 'FRUIT & TREE NUT TOTALS', 'APPLES' ],
  'SOUTH DAKOTA': [ 'FRUIT & TREE NUT TOTALS', 'APPLES' ],
  NEVADA: [ 'FRUIT & TREE NUT TOTALS', 'APPLES' ] }],
'FIELD%20CROPS':{ 'SOUTH CAROLINA': 
   [ 'TOBACCO',
     'COTTON',
     'WHEAT',
     'PEANUTS',
     'SOYBEANS',
     'OATS',
     'HAY',
     'CORN',
     'SORGHUM',
     'HAY & HAYLAGE',
     'FIELD CROP TOTALS' ],
  INDIANA: 
   [ 'HAY',
     'SOYBEANS',
     'CORN',
     'WHEAT',
     'OATS',
     'TOBACCO',
     'MINT',
     'FIELD CROP TOTALS',
     'HAY & HAYLAGE' ],
  OKLAHOMA: 
   [ 'HAY',
     'WHEAT',
     'HAY & HAYLAGE',
     'CORN',
     'SOYBEANS',
     'FIELD CROP TOTALS',
     'OATS',
     'SORGHUM',
     'PEANUTS',
     'SUNFLOWER',
     'COTTON',
     'RYE',
     'CANOLA',
     'BARLEY' ],
  KENTUCKY: 
   [ 'WHEAT',
     'HAY',
     'TOBACCO',
     'BARLEY',
     'SOYBEANS',
     'SORGHUM',
     'CORN',
     'HAY & HAYLAGE',
     'FIELD CROP TOTALS' ],
  MISSOURI: 
   [ 'COTTON',
     'HAY',
     'RICE',
     'TOBACCO',
     'CORN',
     'WHEAT',
     'FIELD CROP TOTALS',
     'SORGHUM',
     'OATS',
     'SOYBEANS',
     'HAYLAGE',
     'HAY & HAYLAGE' ],
  ARKANSAS: 
   [ 'RICE',
     'COTTON',
     'CORN',
     'OATS',
     'SOYBEANS',
     'WHEAT',
     'HAY',
     'SORGHUM',
     'FIELD CROP TOTALS',
     'HAY & HAYLAGE' ],
  DELAWARE: 
   [ 'WHEAT',
     'CORN',
     'FIELD CROP TOTALS',
     'SOYBEANS',
     'HAY',
     'BARLEY',
     'SORGHUM',
     'HAY & HAYLAGE' ],
  'OTHER STATES': 
   [ 'SUNFLOWER',
     'SAFFLOWER',
     'SORGHUM',
     'RYE',
     'CANOLA',
     'HAY',
     'WHEAT',
     'BEANS',
     'CORN',
     'OATS',
     'TOBACCO',
     'BARLEY',
     'SOYBEANS',
     'MINT',
     'COTTON',
     'PEANUTS',
     'RICE',
     'PEAS' ],
  'NORTH DAKOTA': 
   [ 'BEANS',
     'SOYBEANS',
     'LENTILS',
     'CORN',
     'HAY',
     'PEAS',
     'OATS',
     'BARLEY',
     'WHEAT',
     'SUNFLOWER',
     'SUGARBEETS',
     'RYE',
     'CANOLA',
     'FLAXSEED',
     'SAFFLOWER',
     'HAY & HAYLAGE',
     'FIELD CROP TOTALS' ],
  FLORIDA: 
   [ 'WHEAT',
     'TOBACCO',
     'SUGARCANE',
     'FIELD CROP TOTALS',
     'COTTON',
     'SOYBEANS',
     'PEANUTS',
     'CORN',
     'HAY',
     'HAY & HAYLAGE' ],
  'SOUTH DAKOTA': 
   [ 'BEANS',
     'HAYLAGE',
     'CORN',
     'SORGHUM',
     'FIELD CROP TOTALS',
     'SOYBEANS',
     'WHEAT',
     'HAY & HAYLAGE',
     'OATS',
     'SUNFLOWER',
     'MILLET',
     'HAY',
     'FLAXSEED',
     'BARLEY',
     'RYE' ],
  IDAHO: 
   [ 'LENTILS',
     'BEANS',
     'WHEAT',
     'SUGARBEETS',
     'PEAS',
     'HOPS',
     'HAY',
     'BARLEY',
     'OATS',
     'MINT',
     'CORN',
     'CANOLA',
     'HAYLAGE',
     'HAY & HAYLAGE',
     'FIELD CROP TOTALS' ],
  WASHINGTON: 
   [ 'LENTILS',
     'FIELD CROP TOTALS',
     'BEANS',
     'CORN',
     'WHEAT',
     'HAY',
     'MINT',
     'HAY & HAYLAGE',
     'HOPS',
     'SUGARBEETS',
     'PEAS',
     'HAYLAGE',
     'BARLEY',
     'OATS',
     'CANOLA' ],
  MONTANA: 
   [ 'LENTILS',
     'SUGARBEETS',
     'BEANS',
     'WHEAT',
     'PEAS',
     'FIELD CROP TOTALS',
     'HAY',
     'FLAXSEED',
     'CANOLA',
     'HAY & HAYLAGE',
     'OATS',
     'CORN',
     'SAFFLOWER',
     'BARLEY',
     'MUSTARD',
     'SUNFLOWER' ],
  KANSAS: 
   [ 'HAY',
     'SOYBEANS',
     'SUNFLOWER',
     'BEANS',
     'SORGHUM',
     'CORN',
     'BARLEY',
     'OATS',
     'WHEAT',
     'COTTON',
     'HAY & HAYLAGE',
     'HAYLAGE',
     'FIELD CROP TOTALS' ],
  MISSISSIPPI: 
   [ 'RICE',
     'COTTON',
     'WHEAT',
     'HAY',
     'PEANUTS',
     'SORGHUM',
     'SOYBEANS',
     'CORN',
     'FIELD CROP TOTALS',
     'HAY & HAYLAGE' ],
  CALIFORNIA: 
   [ 'RICE',
     'SORGHUM',
     'SUNFLOWER',
     'COTTON',
     'BEANS',
     'HAY',
     'CORN',
     'HAYLAGE',
     'WHEAT',
     'OATS',
     'BARLEY',
     'SUGARBEETS',
     'SAFFLOWER',
     'HAY & HAYLAGE',
     'FIELD CROP TOTALS',
     'MINT' ],
  TEXAS: 
   [ 'HAY',
     'BEANS',
     'COTTON',
     'CORN',
     'OATS',
     'RICE',
     'SUNFLOWER',
     'SORGHUM',
     'FIELD CROP TOTALS',
     'WHEAT',
     'SOYBEANS',
     'PEANUTS',
     'SUGARCANE',
     'HAYLAGE',
     'HAY & HAYLAGE' ],
  ILLINOIS: 
   [ 'HAYLAGE',
     'HAY & HAYLAGE',
     'CORN',
     'WHEAT',
     'SORGHUM',
     'OATS',
     'HAY',
     'SOYBEANS',
     'FIELD CROP TOTALS' ],
  'NEW MEXICO': 
   [ 'BEANS',
     'HAY',
     'COTTON',
     'CORN',
     'WHEAT',
     'PEANUTS',
     'SORGHUM',
     'FIELD CROP TOTALS',
     'HAYLAGE',
     'HAY & HAYLAGE' ],
  CONNECTICUT: 
   [ 'HAY',
     'TOBACCO',
     'FIELD CROP TOTALS',
     'MAPLE SYRUP',
     'CORN',
     'HAY & HAYLAGE' ],
  NEVADA: 
   [ 'HAY',
     'CORN',
     'BARLEY',
     'WHEAT',
     'FIELD CROP TOTALS',
     'HAY & HAYLAGE' ],
  UTAH: 
   [ 'BARLEY',
     'FIELD CROP TOTALS',
     'HAY',
     'CORN',
     'SAFFLOWER',
     'WHEAT',
     'BEANS',
     'OATS',
     'HAY & HAYLAGE' ],
  OREGON: 
   [ 'BEANS',
     'PEAS',
     'HOPS',
     'MINT',
     'SUGARBEETS',
     'OATS',
     'BARLEY',
     'CORN',
     'HAY',
     'WHEAT',
     'CANOLA',
     'FIELD CROP TOTALS',
     'HAY & HAYLAGE' ],
  MASSACHUSETTS: 
   [ 'HAY',
     'MAPLE SYRUP',
     'TOBACCO',
     'HAY & HAYLAGE',
     'FIELD CROP TOTALS',
     'CORN' ],
  MICHIGAN: 
   [ 'HAY',
     'BEANS',
     'SOYBEANS',
     'MINT',
     'HAY & HAYLAGE',
     'WHEAT',
     'OATS',
     'MAPLE SYRUP',
     'BARLEY',
     'CORN',
     'SUGARBEETS',
     'FIELD CROP TOTALS',
     'HAYLAGE' ],
  'NEW JERSEY': 
   [ 'CORN',
     'FIELD CROP TOTALS',
     'SOYBEANS',
     'HAY',
     'BARLEY',
     'WHEAT',
     'HAY & HAYLAGE' ],
  VIRGINIA: 
   [ 'TOBACCO',
     'COTTON',
     'HAY',
     'WHEAT',
     'SORGHUM',
     'OATS',
     'PEANUTS',
     'SOYBEANS',
     'CORN',
     'BARLEY',
     'HAY & HAYLAGE',
     'FIELD CROP TOTALS' ],
  'NORTH CAROLINA': 
   [ 'PEANUTS',
     'COTTON',
     'TOBACCO',
     'HAY & HAYLAGE',
     'HAY',
     'CORN',
     'WHEAT',
     'BARLEY',
     'OATS',
     'SORGHUM',
     'SOYBEANS',
     'FIELD CROP TOTALS' ],
  IOWA: 
   [ 'SOYBEANS',
     'HAY',
     'CORN',
     'OATS',
     'WHEAT',
     'HAY & HAYLAGE',
     'HAYLAGE',
     'FIELD CROP TOTALS' ],
  WISCONSIN: 
   [ 'TOBACCO',
     'SOYBEANS',
     'BEANS',
     'WHEAT',
     'BARLEY',
     'HAY',
     'MAPLE SYRUP',
     'HAY & HAYLAGE',
     'CORN',
     'OATS',
     'MINT',
     'FIELD CROP TOTALS',
     'HAYLAGE' ],
  MARYLAND: 
   [ 'CORN',
     'BARLEY',
     'FIELD CROP TOTALS',
     'WHEAT',
     'HAY',
     'SOYBEANS',
     'TOBACCO',
     'SORGHUM',
     'HAY & HAYLAGE' ],
  GEORGIA: 
   [ 'PEANUTS',
     'TOBACCO',
     'COTTON',
     'SOYBEANS',
     'HAY',
     'WHEAT',
     'CORN',
     'RYE',
     'SORGHUM',
     'OATS',
     'FIELD CROP TOTALS',
     'HAY & HAYLAGE' ],
  MINNESOTA: 
   [ 'HAY',
     'BEANS',
     'WHEAT',
     'BARLEY',
     'SUNFLOWER',
     'HAY & HAYLAGE',
     'SUGARBEETS',
     'CANOLA',
     'SOYBEANS',
     'CORN',
     'OATS',
     'FLAXSEED',
     'HAYLAGE',
     'FIELD CROP TOTALS' ],
  'WEST VIRGINIA': 
   [ 'TOBACCO',
     'WHEAT',
     'HAY',
     'SOYBEANS',
     'CORN',
     'HAY & HAYLAGE',
     'FIELD CROP TOTALS',
     'HAYLAGE' ],
  OHIO: 
   [ 'TOBACCO',
     'WHEAT',
     'FIELD CROP TOTALS',
     'MAPLE SYRUP',
     'CORN',
     'HAY',
     'OATS',
     'SOYBEANS',
     'SUGARBEETS',
     'BARLEY',
     'HAYLAGE',
     'HAY & HAYLAGE' ],
  TENNESSEE: 
   [ 'COTTON',
     'HAY',
     'TOBACCO',
     'WHEAT',
     'SORGHUM',
     'CORN',
     'SOYBEANS',
     'FIELD CROP TOTALS',
     'HAY & HAYLAGE' ],
  NEBRASKA: 
   [ 'BEANS',
     'CORN',
     'WHEAT',
     'SORGHUM',
     'SOYBEANS',
     'SUNFLOWER',
     'HAY',
     'SUGARBEETS',
     'OATS',
     'HAY & HAYLAGE',
     'BARLEY',
     'MILLET',
     'HAYLAGE',
     'FIELD CROP TOTALS' ],
  WYOMING: 
   [ 'BEANS',
     'SUGARBEETS',
     'WHEAT',
     'HAY',
     'CORN',
     'BARLEY',
     'OATS',
     'FIELD CROP TOTALS',
     'HAY & HAYLAGE' ],
  COLORADO: 
   [ 'BEANS',
     'WHEAT',
     'HAY',
     'SUNFLOWER',
     'OATS',
     'CORN',
     'SUGARBEETS',
     'SORGHUM',
     'BARLEY',
     'MILLET',
     'FIELD CROP TOTALS',
     'HAY & HAYLAGE' ],
  ARIZONA: 
   [ 'HAY',
     'WHEAT',
     'COTTON',
     'CORN',
     'SORGHUM',
     'BARLEY',
     'BEANS',
     'HAY & HAYLAGE',
     'FIELD CROP TOTALS' ],
  VERMONT: 
   [ 'MAPLE SYRUP',
     'HAY',
     'CORN',
     'HAYLAGE',
     'FIELD CROP TOTALS',
     'HAY & HAYLAGE' ],
  LOUISIANA: 
   [ 'CORN',
     'COTTON',
     'RICE',
     'HAY',
     'SUGARCANE',
     'SORGHUM',
     'WHEAT',
     'SOYBEANS',
     'FIELD CROP TOTALS',
     'HAY & HAYLAGE' ],
  'RHODE ISLAND': [ 'HAY', 'CORN', 'FIELD CROP TOTALS', 'HAY & HAYLAGE' ],
  'NEW YORK': 
   [ 'CORN',
     'OATS',
     'FIELD CROP TOTALS',
     'HAY',
     'BEANS',
     'MAPLE SYRUP',
     'WHEAT',
     'BARLEY',
     'SOYBEANS',
     'HAY & HAYLAGE',
     'HAYLAGE' ],
  ALABAMA: 
   [ 'OATS',
     'PEANUTS',
     'COTTON',
     'SORGHUM',
     'SOYBEANS',
     'HAY',
     'FIELD CROP TOTALS',
     'CORN',
     'WHEAT',
     'HAY & HAYLAGE' ],
  HAWAII: [ 'SUGARCANE', 'TARO', 'FIELD CROP TOTALS' ],
  PENNSYLVANIA: 
   [ 'HAY & HAYLAGE',
     'OATS',
     'WHEAT',
     'HAYLAGE',
     'SOYBEANS',
     'CORN',
     'HAY',
     'SORGHUM',
     'BARLEY',
     'TOBACCO',
     'MAPLE SYRUP',
     'FIELD CROP TOTALS' ],
  'NEW HAMPSHIRE': 
   [ 'HAY',
     'HAY & HAYLAGE',
     'MAPLE SYRUP',
     'CORN',
     'FIELD CROP TOTALS' ],
  MAINE: 
   [ 'HAY',
     'OATS',
     'MAPLE SYRUP',
     'BARLEY',
     'HAY & HAYLAGE',
     'FIELD CROP TOTALS',
     'CORN' ],
  ALASKA: [ 'HAY', 'BARLEY', 'OATS' ] },
  'HORTICULTURE':{},
  'VEGETABLES':{ COLORADO: 
   [ 'POTATOES',
     'MELONS',
     'CABBAGE',
     'CARROTS',
     'SWEET CORN',
     'SPINACH',
     'LETTUCE',
     'ONIONS',
     'VEGETABLE TOTALS',
     'CUCUMBERS' ],
  CALIFORNIA: 
   [ 'POTATOES',
     'SWEET POTATOES',
     'ONIONS',
     'PEPPERS',
     'BROCCOLI',
     'CAULIFLOWER',
     'CELERY',
     'SWEET CORN',
     'CUCUMBERS',
     'PUMPKINS',
     'SPINACH',
     'SQUASH',
     'TOMATOES',
     'VEGETABLE TOTALS',
     'ASPARAGUS',
     'CARROTS',
     'GARLIC',
     'LETTUCE',
     'GREENS',
     'ARTICHOKES',
     'MELONS',
     'BEANS',
     'CABBAGE',
     'ESCAROLE & ENDIVE',
     'BRUSSELS SPROUTS',
     'RADISHES',
     'EGGPLANT' ],
  ARIZONA: 
   [ 'POTATOES',
     'MELONS',
     'PEPPERS',
     'CAULIFLOWER',
     'CARROTS',
     'VEGETABLE TOTALS',
     'BROCCOLI',
     'CABBAGE',
     'LETTUCE',
     'SPINACH',
     'ONIONS' ],
  ALABAMA: 
   [ 'POTATOES',
     'SWEET POTATOES',
     'MELONS',
     'SWEET CORN',
     'OKRA',
     'BEANS',
     'GREENS',
     'TOMATOES',
     'VEGETABLE TOTALS' ],
  MONTANA: [ 'POTATOES' ],
  'NORTH DAKOTA': [ 'POTATOES' ],
  MICHIGAN: 
   [ 'POTATOES',
     'ONIONS',
     'PEPPERS',
     'CARROTS',
     'CELERY',
     'ASPARAGUS',
     'CABBAGE',
     'PUMPKINS',
     'CUCUMBERS',
     'SWEET CORN',
     'SQUASH',
     'BEANS',
     'CAULIFLOWER',
     'VEGETABLE TOTALS',
     'MELONS',
     'TOMATOES',
     'RADISHES' ],
  MAINE: [ 'POTATOES', 'SWEET CORN', 'VEGETABLE TOTALS' ],
  MISSOURI: [ 'POTATOES', 'SWEET POTATOES', 'MELONS', 'VEGETABLE TOTALS' ],
  MASSACHUSETTS: 
   [ 'POTATOES',
     'SWEET CORN',
     'EGGPLANT',
     'TOMATOES',
     'VEGETABLE TOTALS' ],
  TENNESSEE: 
   [ 'POTATOES',
     'SWEET POTATOES',
     'BEANS',
     'SQUASH',
     'VEGETABLE TOTALS',
     'TOMATOES' ],
  NEVADA: [ 'POTATOES', 'ONIONS', 'GARLIC', 'VEGETABLE TOTALS' ],
  INDIANA: 
   [ 'POTATOES',
     'SWEET POTATOES',
     'SWEET CORN',
     'BEANS',
     'CUCUMBERS',
     'MELONS',
     'TOMATOES',
     'VEGETABLE TOTALS' ],
  MISSISSIPPI: [ 'POTATOES', 'SWEET POTATOES', 'MELONS', 'VEGETABLE TOTALS' ],
  'SOUTH CAROLINA': 
   [ 'POTATOES',
     'SWEET POTATOES',
     'MELONS',
     'BEANS',
     'SQUASH',
     'GREENS',
     'CUCUMBERS',
     'VEGETABLE TOTALS',
     'TOMATOES' ],
  FLORIDA: 
   [ 'POTATOES',
     'SWEET POTATOES',
     'MELONS',
     'CABBAGE',
     'SWEET CORN',
     'CUCUMBERS',
     'BEANS',
     'PEPPERS',
     'EGGPLANT',
     'ESCAROLE & ENDIVE',
     'SQUASH',
     'OKRA',
     'RADISHES',
     'VEGETABLE TOTALS',
     'TOMATOES',
     'LETTUCE',
     'CARROTS' ],
  WASHINGTON: 
   [ 'POTATOES',
     'ONIONS',
     'PEAS',
     'SWEET CORN',
     'VEGETABLE TOTALS',
     'CARROTS',
     'ASPARAGUS',
     'LETTUCE' ],
  ILLINOIS: 
   [ 'POTATOES',
     'SWEET POTATOES',
     'BEANS',
     'CABBAGE',
     'SWEET CORN',
     'ASPARAGUS',
     'VEGETABLE TOTALS',
     'PUMPKINS' ],
  'WEST VIRGINIA': [ 'POTATOES', 'SWEET POTATOES' ],
  'NEW MEXICO': 
   [ 'POTATOES',
     'SWEET POTATOES',
     'ONIONS',
     'PEPPERS',
     'LETTUCE',
     'VEGETABLE TOTALS' ],
  'SOUTH DAKOTA': [ 'POTATOES' ],
  MARYLAND: 
   [ 'POTATOES',
     'SWEET POTATOES',
     'MELONS',
     'SWEET CORN',
     'BEANS',
     'CABBAGE',
     'CUCUMBERS',
     'VEGETABLE TOTALS',
     'SPINACH',
     'TOMATOES' ],
  'NEW JERSEY': 
   [ 'POTATOES',
     'SWEET POTATOES',
     'PEPPERS',
     'CABBAGE',
     'BEANS',
     'SWEET CORN',
     'VEGETABLE TOTALS',
     'SQUASH',
     'LETTUCE',
     'CUCUMBERS',
     'ASPARAGUS',
     'SPINACH',
     'EGGPLANT',
     'ESCAROLE & ENDIVE',
     'TOMATOES' ],
  IOWA: [ 'POTATOES', 'SWEET POTATOES', 'VEGETABLE TOTALS' ],
  GEORGIA: 
   [ 'POTATOES',
     'SWEET POTATOES',
     'MELONS',
     'ONIONS',
     'CABBAGE',
     'CUCUMBERS',
     'BEANS',
     'SQUASH',
     'GREENS',
     'SWEET CORN',
     'CARROTS',
     'PEPPERS',
     'EGGPLANT',
     'TOMATOES',
     'VEGETABLE TOTALS',
     'OKRA' ],
  NEBRASKA: [ 'POTATOES' ],
  KANSAS: [ 'POTATOES', 'SWEET POTATOES' ],
  LOUISIANA: 
   [ 'POTATOES',
     'SWEET POTATOES',
     'MELONS',
     'VEGETABLE TOTALS',
     'PEPPERS',
     'TOMATOES' ],
  WYOMING: [ 'POTATOES' ],
  MINNESOTA: 
   [ 'POTATOES',
     'PEAS',
     'CARROTS',
     'VEGETABLE TOTALS',
     'SWEET CORN',
     'ONIONS',
     'BEANS' ],
  IDAHO: [ 'POTATOES', 'SWEET CORN', 'ONIONS', 'VEGETABLE TOTALS' ],
  DELAWARE: 
   [ 'POTATOES',
     'SWEET POTATOES',
     'SWEET CORN',
     'PEAS',
     'MELONS',
     'VEGETABLE TOTALS',
     'BEANS' ],
  TEXAS: 
   [ 'SWEET POTATOES',
     'POTATOES',
     'MELONS',
     'ONIONS',
     'CABBAGE',
     'SWEET CORN',
     'GREENS',
     'CUCUMBERS',
     'CELERY',
     'PEPPERS',
     'SPINACH',
     'SQUASH',
     'OKRA',
     'VEGETABLE TOTALS',
     'CARROTS',
     'TOMATOES',
     'BROCCOLI' ],
  'RHODE ISLAND': [ 'POTATOES', 'SWEET CORN', 'VEGETABLE TOTALS' ],
  'NEW YORK': 
   [ 'POTATOES',
     'ONIONS',
     'CAULIFLOWER',
     'SWEET CORN',
     'CUCUMBERS',
     'BEANS',
     'CABBAGE',
     'PUMPKINS',
     'SQUASH',
     'CARROTS',
     'SPINACH',
     'EGGPLANT',
     'PEAS',
     'BEETS',
     'LETTUCE',
     'VEGETABLE TOTALS',
     'ESCAROLE & ENDIVE',
     'PEPPERS',
     'TOMATOES' ],
  VERMONT: [ 'POTATOES', 'SWEET CORN', 'VEGETABLE TOTALS' ],
  'NORTH CAROLINA': 
   [ 'POTATOES',
     'SWEET POTATOES',
     'PEPPERS',
     'CABBAGE',
     'SQUASH',
     'GREENS',
     'SWEET CORN',
     'VEGETABLE TOTALS',
     'CUCUMBERS',
     'EGGPLANT',
     'MELONS',
     'BEANS',
     'TOMATOES' ],
  VIRGINIA: 
   [ 'SWEET POTATOES',
     'POTATOES',
     'MELONS',
     'VEGETABLE TOTALS',
     'SWEET CORN',
     'CUCUMBERS',
     'BEANS',
     'CABBAGE',
     'PEPPERS',
     'TOMATOES' ],
  OREGON: 
   [ 'POTATOES',
     'SWEET CORN',
     'VEGETABLE TOTALS',
     'BEANS',
     'CARROTS',
     'ASPARAGUS',
     'SQUASH',
     'CAULIFLOWER',
     'PEAS',
     'GARLIC' ],
  ARKANSAS: 
   [ 'SWEET POTATOES',
     'POTATOES',
     'VEGETABLE TOTALS',
     'MELONS',
     'TOMATOES' ],
  OHIO: 
   [ 'POTATOES',
     'PEPPERS',
     'CABBAGE',
     'PUMPKINS',
     'VEGETABLE TOTALS',
     'TOMATOES',
     'SQUASH',
     'ESCAROLE & ENDIVE',
     'CUCUMBERS',
     'SWEET CORN',
     'ONIONS',
     'RADISHES',
     'LETTUCE',
     'MELONS',
     'BEANS',
     'GREENS',
     'PEAS' ],
  UTAH: [ 'POTATOES', 'ONIONS', 'VEGETABLE TOTALS' ],
  OKLAHOMA: [ 'POTATOES', 'SWEET POTATOES', 'MELONS', 'VEGETABLE TOTALS' ],
  CONNECTICUT: 
   [ 'POTATOES',
     'SWEET CORN',
     'VEGETABLE TOTALS',
     'EGGPLANT',
     'TOMATOES' ],
  WISCONSIN: 
   [ 'POTATOES',
     'PEAS',
     'CABBAGE',
     'CARROTS',
     'SWEET CORN',
     'BEETS',
     'VEGETABLE TOTALS',
     'CUCUMBERS',
     'ONIONS',
     'BEANS' ],
  PENNSYLVANIA: 
   [ 'POTATOES',
     'BEANS',
     'CABBAGE',
     'SWEET CORN',
     'MELONS',
     'PUMPKINS',
     'VEGETABLE TOTALS',
     'PEPPERS',
     'TOMATOES' ],
  'NEW HAMPSHIRE': [ 'POTATOES', 'SWEET CORN', 'VEGETABLE TOTALS' ],
  KENTUCKY: [ 'POTATOES', 'SWEET POTATOES' ],
  ALASKA: [ 'POTATOES' ],
  HAWAII: 
   [ 'GINGER ROOT',
     'CABBAGE',
     'BEANS',
     'MELONS',
     'CUCUMBERS',
     'EGGPLANT',
     'TOMATOES',
     'VEGETABLE TOTALS' ],
  'OTHER STATES': 
   [ 'ONIONS',
     'BEANS',
     'CARROTS',
     'ASPARAGUS',
     'BROCCOLI',
     'SPINACH',
     'CABBAGE',
     'CUCUMBERS',
     'CAULIFLOWER',
     'TOMATOES',
     'SWEET CORN',
     'EGGPLANT',
     'LETTUCE',
     'PEAS',
     'GREENS',
     'BEETS',
     'ESCAROLE & ENDIVE',
     'VEGETABLE TOTALS',
     'MELONS',
     'POTATOES',
     'SWEET POTATOES' ] }
}

