{ COLORADO: 
   [ 'POTATOES',
     'MELONS',
     'CABBAGE',
     'CARROTS',
     'SWEET CORN',
     'SPINACH',
     'LETTUCE',
     'ONIONS',
     'VEGETABLE TOTALS',
     'CUCUMBERS' ],
  CALIFORNIA: 
   [ 'POTATOES',
     'SWEET POTATOES',
     'ONIONS',
     'PEPPERS',
     'BROCCOLI',
     'CAULIFLOWER',
     'CELERY',
     'SWEET CORN',
     'CUCUMBERS',
     'PUMPKINS',
     'SPINACH',
     'SQUASH',
     'TOMATOES',
     'VEGETABLE TOTALS',
     'ASPARAGUS',
     'CARROTS',
     'GARLIC',
     'LETTUCE',
     'GREENS',
     'ARTICHOKES',
     'MELONS',
     'BEANS',
     'CABBAGE',
     'ESCAROLE & ENDIVE',
     'BRUSSELS SPROUTS',
     'RADISHES',
     'EGGPLANT' ],
  ARIZONA: 
   [ 'POTATOES',
     'MELONS',
     'PEPPERS',
     'CAULIFLOWER',
     'CARROTS',
     'VEGETABLE TOTALS',
     'BROCCOLI',
     'CABBAGE',
     'LETTUCE',
     'SPINACH',
     'ONIONS' ],
  ALABAMA: 
   [ 'POTATOES',
     'SWEET POTATOES',
     'MELONS',
     'SWEET CORN',
     'OKRA',
     'BEANS',
     'GREENS',
     'TOMATOES',
     'VEGETABLE TOTALS' ],
  MONTANA: [ 'POTATOES' ],
  NORTH DAKOTA: [ 'POTATOES' ],
  MICHIGAN: 
   [ 'POTATOES',
     'ONIONS',
     'PEPPERS',
     'CARROTS',
     'CELERY',
     'ASPARAGUS',
     'CABBAGE',
     'PUMPKINS',
     'CUCUMBERS',
     'SWEET CORN',
     'SQUASH',
     'BEANS',
     'CAULIFLOWER',
     'VEGETABLE TOTALS',
     'MELONS',
     'TOMATOES',
     'RADISHES' ],
  MAINE: [ 'POTATOES', 'SWEET CORN', 'VEGETABLE TOTALS' ],
  MISSOURI: [ 'POTATOES', 'SWEET POTATOES', 'MELONS', 'VEGETABLE TOTALS' ],
  MASSACHUSETTS: 
   [ 'POTATOES',
     'SWEET CORN',
     'EGGPLANT',
     'TOMATOES',
     'VEGETABLE TOTALS' ],
  TENNESSEE: 
   [ 'POTATOES',
     'SWEET POTATOES',
     'BEANS',
     'SQUASH',
     'VEGETABLE TOTALS',
     'TOMATOES' ],
  NEVADA: [ 'POTATOES', 'ONIONS', 'GARLIC', 'VEGETABLE TOTALS' ],
  INDIANA: 
   [ 'POTATOES',
     'SWEET POTATOES',
     'SWEET CORN',
     'BEANS',
     'CUCUMBERS',
     'MELONS',
     'TOMATOES',
     'VEGETABLE TOTALS' ],
  MISSISSIPPI: [ 'POTATOES', 'SWEET POTATOES', 'MELONS', 'VEGETABLE TOTALS' ],
  SOUTH CAROLINA: 
   [ 'POTATOES',
     'SWEET POTATOES',
     'MELONS',
     'BEANS',
     'SQUASH',
     'GREENS',
     'CUCUMBERS',
     'VEGETABLE TOTALS',
     'TOMATOES' ],
  FLORIDA: 
   [ 'POTATOES',
     'SWEET POTATOES',
     'MELONS',
     'CABBAGE',
     'SWEET CORN',
     'CUCUMBERS',
     'BEANS',
     'PEPPERS',
     'EGGPLANT',
     'ESCAROLE & ENDIVE',
     'SQUASH',
     'OKRA',
     'RADISHES',
     'VEGETABLE TOTALS',
     'TOMATOES',
     'LETTUCE',
     'CARROTS' ],
  WASHINGTON: 
   [ 'POTATOES',
     'ONIONS',
     'PEAS',
     'SWEET CORN',
     'VEGETABLE TOTALS',
     'CARROTS',
     'ASPARAGUS',
     'LETTUCE' ],
  ILLINOIS: 
   [ 'POTATOES',
     'SWEET POTATOES',
     'BEANS',
     'CABBAGE',
     'SWEET CORN',
     'ASPARAGUS',
     'VEGETABLE TOTALS',
     'PUMPKINS' ],
  WEST VIRGINIA: [ 'POTATOES', 'SWEET POTATOES' ],
  NEW MEXICO: 
   [ 'POTATOES',
     'SWEET POTATOES',
     'ONIONS',
     'PEPPERS',
     'LETTUCE',
     'VEGETABLE TOTALS' ],
  SOUTH DAKOTA: [ 'POTATOES' ],
  MARYLAND: 
   [ 'POTATOES',
     'SWEET POTATOES',
     'MELONS',
     'SWEET CORN',
     'BEANS',
     'CABBAGE',
     'CUCUMBERS',
     'VEGETABLE TOTALS',
     'SPINACH',
     'TOMATOES' ],
  NEW JERSEY: 
   [ 'POTATOES',
     'SWEET POTATOES',
     'PEPPERS',
     'CABBAGE',
     'BEANS',
     'SWEET CORN',
     'VEGETABLE TOTALS',
     'SQUASH',
     'LETTUCE',
     'CUCUMBERS',
     'ASPARAGUS',
     'SPINACH',
     'EGGPLANT',
     'ESCAROLE & ENDIVE',
     'TOMATOES' ],
  IOWA: [ 'POTATOES', 'SWEET POTATOES', 'VEGETABLE TOTALS' ],
  GEORGIA: 
   [ 'POTATOES',
     'SWEET POTATOES',
     'MELONS',
     'ONIONS',
     'CABBAGE',
     'CUCUMBERS',
     'BEANS',
     'SQUASH',
     'GREENS',
     'SWEET CORN',
     'CARROTS',
     'PEPPERS',
     'EGGPLANT',
     'TOMATOES',
     'VEGETABLE TOTALS',
     'OKRA' ],
  NEBRASKA: [ 'POTATOES' ],
  KANSAS: [ 'POTATOES', 'SWEET POTATOES' ],
  LOUISIANA: 
   [ 'POTATOES',
     'SWEET POTATOES',
     'MELONS',
     'VEGETABLE TOTALS',
     'PEPPERS',
     'TOMATOES' ],
  WYOMING: [ 'POTATOES' ],
  MINNESOTA: 
   [ 'POTATOES',
     'PEAS',
     'CARROTS',
     'VEGETABLE TOTALS',
     'SWEET CORN',
     'ONIONS',
     'BEANS' ],
  IDAHO: [ 'POTATOES', 'SWEET CORN', 'ONIONS', 'VEGETABLE TOTALS' ],
  DELAWARE: 
   [ 'POTATOES',
     'SWEET POTATOES',
     'SWEET CORN',
     'PEAS',
     'MELONS',
     'VEGETABLE TOTALS',
     'BEANS' ],
  TEXAS: 
   [ 'SWEET POTATOES',
     'POTATOES',
     'MELONS',
     'ONIONS',
     'CABBAGE',
     'SWEET CORN',
     'GREENS',
     'CUCUMBERS',
     'CELERY',
     'PEPPERS',
     'SPINACH',
     'SQUASH',
     'OKRA',
     'VEGETABLE TOTALS',
     'CARROTS',
     'TOMATOES',
     'BROCCOLI' ],
  RHODE ISLAND: [ 'POTATOES', 'SWEET CORN', 'VEGETABLE TOTALS' ],
  NEW YORK: 
   [ 'POTATOES',
     'ONIONS',
     'CAULIFLOWER',
     'SWEET CORN',
     'CUCUMBERS',
     'BEANS',
     'CABBAGE',
     'PUMPKINS',
     'SQUASH',
     'CARROTS',
     'SPINACH',
     'EGGPLANT',
     'PEAS',
     'BEETS',
     'LETTUCE',
     'VEGETABLE TOTALS',
     'ESCAROLE & ENDIVE',
     'PEPPERS',
     'TOMATOES' ],
  VERMONT: [ 'POTATOES', 'SWEET CORN', 'VEGETABLE TOTALS' ],
  NORTH CAROLINA: 
   [ 'POTATOES',
     'SWEET POTATOES',
     'PEPPERS',
     'CABBAGE',
     'SQUASH',
     'GREENS',
     'SWEET CORN',
     'VEGETABLE TOTALS',
     'CUCUMBERS',
     'EGGPLANT',
     'MELONS',
     'BEANS',
     'TOMATOES' ],
  VIRGINIA: 
   [ 'SWEET POTATOES',
     'POTATOES',
     'MELONS',
     'VEGETABLE TOTALS',
     'SWEET CORN',
     'CUCUMBERS',
     'BEANS',
     'CABBAGE',
     'PEPPERS',
     'TOMATOES' ],
  OREGON: 
   [ 'POTATOES',
     'SWEET CORN',
     'VEGETABLE TOTALS',
     'BEANS',
     'CARROTS',
     'ASPARAGUS',
     'SQUASH',
     'CAULIFLOWER',
     'PEAS',
     'GARLIC' ],
  ARKANSAS: 
   [ 'SWEET POTATOES',
     'POTATOES',
     'VEGETABLE TOTALS',
     'MELONS',
     'TOMATOES' ],
  OHIO: 
   [ 'POTATOES',
     'PEPPERS',
     'CABBAGE',
     'PUMPKINS',
     'VEGETABLE TOTALS',
     'TOMATOES',
     'SQUASH',
     'ESCAROLE & ENDIVE',
     'CUCUMBERS',
     'SWEET CORN',
     'ONIONS',
     'RADISHES',
     'LETTUCE',
     'MELONS',
     'BEANS',
     'GREENS',
     'PEAS' ],
  UTAH: [ 'POTATOES', 'ONIONS', 'VEGETABLE TOTALS' ],
  OKLAHOMA: [ 'POTATOES', 'SWEET POTATOES', 'MELONS', 'VEGETABLE TOTALS' ],
  CONNECTICUT: 
   [ 'POTATOES',
     'SWEET CORN',
     'VEGETABLE TOTALS',
     'EGGPLANT',
     'TOMATOES' ],
  WISCONSIN: 
   [ 'POTATOES',
     'PEAS',
     'CABBAGE',
     'CARROTS',
     'SWEET CORN',
     'BEETS',
     'VEGETABLE TOTALS',
     'CUCUMBERS',
     'ONIONS',
     'BEANS' ],
  PENNSYLVANIA: 
   [ 'POTATOES',
     'BEANS',
     'CABBAGE',
     'SWEET CORN',
     'MELONS',
     'PUMPKINS',
     'VEGETABLE TOTALS',
     'PEPPERS',
     'TOMATOES' ],
  NEW HAMPSHIRE: [ 'POTATOES', 'SWEET CORN', 'VEGETABLE TOTALS' ],
  KENTUCKY: [ 'POTATOES', 'SWEET POTATOES' ],
  ALASKA: [ 'POTATOES' ],
  HAWAII: 
   [ 'GINGER ROOT',
     'CABBAGE',
     'BEANS',
     'MELONS',
     'CUCUMBERS',
     'EGGPLANT',
     'TOMATOES',
     'VEGETABLE TOTALS' ],
  OTHER STATES: 
   [ 'ONIONS',
     'BEANS',
     'CARROTS',
     'ASPARAGUS',
     'BROCCOLI',
     'SPINACH',
     'CABBAGE',
     'CUCUMBERS',
     'CAULIFLOWER',
     'TOMATOES',
     'SWEET CORN',
     'EGGPLANT',
     'LETTUCE',
     'PEAS',
     'GREENS',
     'BEETS',
     'ESCAROLE & ENDIVE',
     'VEGETABLE TOTALS',
     'MELONS',
     'POTATOES',
     'SWEET POTATOES' ] }